### ISSUE TITLE
Revamp Question Card UI

### ISSUE THREAD

**Issue by jobenjada** [formbricks/design#16]
Based on the great [market research ](https://github.com/formbricks/design/issues/15)and our own UX we propose to revamp the Question Card.

### Problems:

1. By default the Card is too tall to fit on a regular laptop screen. This makes it more difficult to grasp how the survey editor works, that you can drag and drop questions etc. Its difficult to get an overview
2. Key actions (move, duplicate, delete) are hidden in a menu
3. Less important settings (required, show question ID) are on first layer

### Design Proposal
![grafik](https://github.com/formbricks/design/assets/72809645/21d27c73-3750-49a7-b9ef-ad452b99f62f)

1: Bring Move, Duplicate and Delete on first layer. Most important settings at the top
2: Move "Required" to the bottom, move question ID to menu (only needed to niche use case of Formbricks). On "Show Question ID" Id open a Modal where you can also update it.
3. Surprisingly few questions come with a description. People don't like reading and keeping it short should be the key. Our UI shouldn't offer a description by default because people might just fill it. The less text, the higher the conversion (assumption). We also shorten the card quite a bit.
4. Reduce CTA size
5. Tone down the Logic feature a bit but keep it on first level. Been adding it to almost every template as it allows for more nuanced questioning. But since its more of an advanced feature, it doesnt need to be the main CTA.

Here is the PenPot: https://design.penpot.app/#/workspace/cdbb0844-1a10-813c-8002-696f8b948bc4/c86728dd-89fd-8169-8002-9e4497beef32?page-id=c86728dd-89fd-8169-8002-9e4497beef33

@sirkotsky I assigned you for some feedback, will implement once we talked it thorugh.
@miiklyy thanks for the good reasearch!

**Comment by sirkotsky** [comment]
Hi @jobenjada, thanks for raising it, and I agree it's a pretty serious issue to tackle. 

There are some points I would like to highlight in your proposed solution that we might need to review before we start building anything, namely:

1. We must avoid using icons with proper labelling. I agree that some action items must be moved up top though, but we should find a better, more accessible solution;
2. Overall, good idea, but perhaps, instead of a modal window, we could have a dropdown, similar to how "Advanced settings" work today. Modal windows are usually not the best idea when it comes to usability;
3. Good solution, and to add to that:
4. "Add option" could also be a link instead of a button. Surprisingly enough, we are not doing anything with the "Button text" in your solution. How often do our users change the button CTA? Wondering if that could be hidden under "Advanced settings"?
5. Also good: the alignment is a bit off to the right, but the visual treatment is good.

I'm a tad packed today, but I'll have a better look at it tomorrow and share some ideas I've got in that regard. Cheers!

**Comment by jobenjada** [comment]
lovely, looking forward to your ideas! :)

**Comment by sirkotsky** [comment]
Appreciate the waiting @jobenjada, here's a quick concept I drew (same Penpot file as you shared, I created a new page for it). It's actually very similar to yours, with just a handful of minor tweaks:

1. I would avoid grouping "Required" and "Add logic" together because it may be slightly confusing: instead, logic can be hidden under Advanced settings, together with things like "CTA text", for instance;
2. Rubbish bin and Duplicate are rather obvious icons, and "Up" and "Down" could either be hidden under a "More" like they are today or displayed with labels (I wouldn't mind either way);
3. Finally, just cleaned up some visual styles for clarity and cleanness. 

![image](https://github.com/formbricks/design/assets/22578094/5ac24797-3401-4d74-b4bb-884e52e60698)

They're mostly minor changes here, this could be the first step, but I wouldn't close the issue on that. Instead, I think we should do more in this regard and start revamping the settings in the meantime. There are plenty of changes we might implement, both from the UI perspective and the experience standpoint.

For now though, we can proceed with your version, just perhaps slightly cleaner. Cheers!

**Comment by jobenjada** [comment]
Shipped by community contribution! :)

https://github.com/formbricks/formbricks/pull/351
